# Site settings
title: Networks 
email: ashinhust.brass@gmail.com  
description: Learn and understand the structure that dominates our 21st century 
baseurl: "hhtps://projects.markinfo.dev/"
url: "https://www.markinfo.dev/"

twitter_username:
github_username: markay12

# Build settings
markdown: kramdown
