# site settings
title: Networking
subtitle: Public and Private Systems
email: ashinhust.brass@gmail.com  
description: Learn the small complications of what runs our 21st century
baseurl: https://www.network.markinfo.dev/ # the subpath of your site, e.g. /blog
url: https://www.markinfo.dev/ # the base hostname & protocol for your site
author: Mark Ashinhust  
street_address: 1106 E. Weber Dr. 
city: Tempe
state: AZ
zip_code: 85281
country: United States of America
phone: (623) 523-2880

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url: 
github_url: https://github.com/Markay12
gitlab_url: https://gitlab.com/
googleplus_url: 
instagram_url: https://www.instagram.com/mark_ashin/
linkedin_url: https://www.linkedin.com/in/mark-ashinhust-3aa5b9193/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
